<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBook-Pro.local" failures="1" tests="5" name="tests.LoginTests" time="60.788" errors="0" timestamp="2020-05-01T20:18:05 PDT" skipped="2">
  <testcase classname="tests.LoginTests" name="loginTest_correctCredentials_loggedToApp" time="14.242"/>
  <system-out/>
  <testcase classname="tests.LoginTests" name="test_Fails" time="12.752">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at tests.LoginTests.test_Fails(LoginTests.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- test_Fails -->
  <system-out/>
  <testcase classname="tests.LoginTests" name="test_Fails" time="10.458">
    <skipped/>
  </testcase> <!-- test_Fails -->
  <system-out/>
  <testcase classname="tests.LoginTests" name="test_Fails" time="10.195">
    <skipped/>
  </testcase> <!-- test_Fails -->
  <system-out/>
  <testcase classname="tests.LoginTests" name="loginTest_incorrectCredentials_notLoggedToApp" time="13.141"/>
  <system-out/>
</testsuite> <!-- tests.LoginTests -->
